export const employeeList = [
    {id:1,
    fullName:"Bobs Jone",
    designation:"Javascript Developer",
    gender:"Male",
    teamName:"Team A"},
    {id:2,
        fullName:"Jilly Balley",
        designation:"Node Developer",
        gender:"Female",
        teamName:"Team A"},
        {id:3,
            fullName:"Jail Shepherd",
            designation:"JavaDeveloper",
            gender:"Female",
            teamName:"Team A"},
            {id:4,
                fullName:"Sam Leynold",
                designation:"React Developer",
                gender:"Male",
                teamName:"Team B"},
                {id:5,
                    fullName:"David Henry",
                    designation:"Dotnet Developer",
                    gender:"Male",
                    teamName:"Team B"},
                    {id:6,
                        fullName:"Sarah Blake",
                        designation:"SQL server DBA",
                        gender:"Female",
                        teamName:"Team B"},
                        {id:7,
                            fullName:"James Bonnet",
                            designation:"Angular Developer",
                            gender:"Male",
                            teamName:"Team C"},
                            {id:8,
                                fullName:"Jesicca Faye",
                                designation:"API Developer",
                                gender:"Female",
                                teamName:"Team C"},
                                {id:9,
                                    fullName:"Lita Stone",
                                    designation:"C++ Developer",
                                    gender:"Female",
                                    teamName:"Team C"},
                                    {id:10,
                                        fullName:"Daniel Young",
                                        designation:"Python Developer",
                                        gender:"Male",
                                        teamName:"Team D"},
                                        {id:11,
                                            fullName:"Aderian Jacob",
                                            designation:"VUE Developer",
                                            gender:"Male",
                                            teamName:"Team D"},
                                            {id:12,
                                                fullName:"Dewid Monroe",
                                                designation:"Grapghic Designer",
                                                gender:"Male",
                                                teamName:"Team D"}
]